"use client"

import Head from 'next/head';
import RoleRedirect from "@/components/Admin/RoleRedirect";
import Sidebar from "@/components/Sidebar";
import useAuthRedirect from "@/hooks/useAuthRedirect";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function AdminLayout({ children }) {
  useAuthRedirect(); 
  
  return (
    <html lang="en">
      <Head>
        <title>Safar Wanderlust- Group Travel Company</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex">
          <Sidebar />
          <main className="flex-1 ">{children}</main>
        </div>
      </body>
    </html>
  );
}